### PR TITLE
Klingon character creation

### PR DESCRIPTION
**Pull request by bcholmes**
This pull request add the following to the character creation process

1. The introduction of Klingon Warrior Types
2. Recognition that some Talents have different names when creating Klingon characters
3. Klingon species, career options, and upbringings/castes
4. The character creation flow (specifically "at what steps do players choose Talents?") is different for Klingons than non-Klingon characters (I've introduced a Workflow concept to help manage this).
5. Additional fields for Lineage and Klingon House

This pull request does not:

1. Use a Klingon-specific character sheet (although the character sheet is populated with Klingon-specific data as necessary).

### CODE REVIEW

**Comment by azjerei** [comment]
Please resolve conflicts and push an update.

**Review by azjerei — APPROVED** [review]
Looks good!

**Comment by bcholmes** [comment]
> Please resolve conflicts and push an update.

Conflicts resolved in 84e2fb6.

**Review by azjerei — APPROVED** [review]
Looks good!

**Pull request merged**
